### ISSUE TITLE
Bootstrapが公開しているアイコンも便利ですよ

### ISSUE THREAD

**Issue by shikishima-TasakiLab** [TatsuyaOkazaki324/designtools#1]
アイコン関係ではBootstrapのものも，なかなか使えます．良ければ追加してください．
https://icons.getbootstrap.com/

それと細かいところですが，誤植を一箇所見つけたのでお知らせしておきます．
https://github.com/TatsuyaOkazaki324/designtools/blob/c3a7bc0cfa86355ed693b87213f751c1a91017e3/index.html#L128
"内容な"→"無いような"

**Comment by TatsuyaOkazaki324** [comment]
ありがとうございます。
コンテンツの追加させていただきます。
